# Required. Project-local tool area name (relative path).
directory: ".sidetable"

tools:
  ghq:
    # Required. Program name to execute.
    # Templating: allowed.
    run: "ghq"
    # Optional. Arguments to inject.
    # Order: tool.prepend + userArgs + tool.append
    # Templating: allowed.
    args:
      # prepend:
      #   - "--some-flag"
      # append:
      # - "--some-flag"
    # Optional. Override environment variables for the tool.
    # Templating: allowed.
    env:
      GHQ_ROOT: "{{.ToolDir}}"
    # Optional. Description shown in `sidetable list`.
    description: "ghq wrapper with project-local root"

# Optional. Aliases for tools.
aliases:
  gg:
    # Required. Target tool name defined in `tools`.
    tool: "ghq"
    # Optional. Arguments to inject.
    # Order: alias.prepend + tool.prepend + userArgs + tool.append + alias.append
    # Templating: allowed.
    args:
      prepend:
        - "get"
        - "-u"
      # append:
      # - "--some-flag"
    # Optional. Description shown in `sidetable list`.
    description: "ghq get shortcut"
